# Generated by Django 2.1.2 on 2018-12-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notetaking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
